config/routes.rb
Rails.application.routes.draw do

  get 'settings/index'
  get 'settings/create_proxy'
  get 'settings/destroy_proxy'
  get 'home/index'
  get 'proxy/index' => 'proxy#index', as: :proxy
  get 'about/index' => 'about#index', as: :about
  get 'store/index' => 'store#index', as: :store

  resources :apps do
    member do
      get :restart
      get :start
      get :stop

      get :db_drop
      get :db_create
      get :db_migrate
      get :db_seed
    end
    collection do
      get :relaunch
      get :start_all
      get :stop_all
    end
  end

  resources :images do
    collection do
      post :destroy_all
    end
  end

  resources :containers do
    member do
      get :restart
      get :stop
      get :start
    end
    collection do
      get :destroy_unused
    end
  end

  root 'home#index'

end

app/models/container.rb
class Container
  include ActiveModel::Model

  attr_accessor :id, :name, :command, :names, :ports, :image, :created_at, :status

  def initialize attributes = {}
    attributes.each{ |k,v| instance_variable_set("@#{ k.to_s.underscore }", v) }
  end

  # Class methods  ##############################################################

  def self.all
    Docker::Container.all(all: true).map{ |i| new(Container::ConvertContainer.new(i).attributes) }
  end

  def self.find id
    new Container::ConvertContainer.new(Docker::Container.get(id)).attributes
  end

  def self.find_by_name name
    all.select{ |c| c.names.include?(name) }.first
  end

  def self.find_by_image name
    all.select{ |c| c.image.names.include?(name) }.first
  end

  def self.first
    all.first
  end

  def self.first_or_create args
    cont = find_by_name args[:name]
    cont.nil? ? create(args) : cont
  end

  def self.run args
    cont = create(args)
    cont.start
  end

  def self.create args
    raise 'image argument must be present.' if args[:image].nil?
    arguments = { 'Image' => args[:image] }
    arguments = arguments.merge({ 'Cmd'  => args[:cmd] })  unless args[:cmd].nil?
    arguments = arguments.merge({ 'name' => args[:name] }) unless args[:name].nil?
    docker_container_tmp = Docker::Container.create(arguments)
    docker_container     = Docker::Container.get(docker_container_tmp.id)
    new Container::ConvertContainer.new(docker_container).attributes
  end

  def self.destroy_unused
    all.each{ |container| container.destroy if %w(exited started).include?(container.status) }
  end

  # Object methods  ##############################################################

  def destroy force = false
    Docker::Container.get(self.id).delete(force: force)
  end

  def start
    Docker::Container.get(id).start
    self
  end

  def stop
    Docker::Container.get(id).stop
    self
  end

  def short_id
    id[0..12]
  end


  #### STATUS

  def started?
    status == 'running'
  end

  def exited?
    status == 'exited'
  end

  def stopped?
    status == 'stopped'
  end

  def can_start?
    exited? || stopped?
  end

  def can_stop?
    started?
  end

end

app/models/container/convert_container.rb
class Container::ConvertContainer
  include ActiveModel

  attr_accessor :id, :name, :command, :names, :ports, :image, :created_at, :status

  def initialize cont
    @id         = cont.id
    @info       = cont.info
    @image      = get_image
    @names      = get_names
    @name       = get_name
    @command    = get_command
    @created_at = get_date_time
    @status     = get_status
    @ports      = get_ports
  end

  def attributes
    { id: @id, names: @names, name: @name, ports: @ports, status: @status, command: @command, image: @image, created_at: @created_at }
  end

  private

  def get_names
    names = @info['Names'].blank? ? [@info['Name']] : [@info['Names']].flatten
    names.compact.map{ |n| n[1..-1] }
  end

  def get_status
    @info['State']
  end

  def get_name
    @names.first
  end

  def get_image
    Image.find(@info["ImageID"]) unless @info["ImageID"].nil?
  end

  def get_ports
    @info['Ports'].map{ |p| "#{ p["IP"] }:#{ p['PrivatePort'] }->#{ p['PublicPort']}/#{ p['Type']}" } unless @info["Ports"].nil?
  end

  def get_command
    @info['Command']
  end

  def get_date_time
    Time.utc(@info['Created']).strftime(HarbourCrane::Application::TIME_FORMAT) unless @info['Created'].nil?
  end
end

app/controllers/containers_controller.rb
require 'docker'
class ContainersController < ApplicationController

  before_action :set_container, only: [:edit, :stop, :destroy, :start]

  def index
    @containers_presenter = ContainerPresenter.new(Container.all).containers
  end

  def show
  end

  def edit
  end

  def stop
    @container.stop
    respond_to do |format|
      format.html { redirect_to containers_path, notice: 'Container was successfully stopped.' }
    end
  end

  def start
    @container.start
    respond_to do |format|
      format.html { redirect_to containers_path, notice: 'Container was successfully started.' }
    end
  end

  def destroy
    @container.destroy
    respond_to do |format|
      format.html { redirect_to containers_path, notice: 'Container was successfully deleted.' }
    end
  end

  def destroy_unused
    Container.destroy_unused
    respond_to do |format|
      format.html { redirect_to containers_path, notice: 'Containers were successfully deleted.' }
    end
  end

  private

  def set_container
    @container = Container.find(params[:id])
  end

end

app/views/containers/edit.html.haml
%h1 Containers#edit
%p Find me in app/views/containers/edit.html.haml
= panel do
  - @container.info.each do |k,v|
    %b= "#{ k }:"
    = "#{ v }"
    %br

app/views/containers/index.html.haml
%h1= glyph_and_text HarbourCrane::Application::Glyph::CONTAINER, "Containers listing"
%p List of containers running in your server
%br
= button_link 'Refresh', glyph: 'refresh', url: containers_path
= button_link 'Remove unused containers', { status: :danger, glyph: 'trash', url: destroy_unused_containers_path }, { title: 'Delete unused containers with exited and started status'}
%br
%br
%table.table
  %tr
    %th Container ID
    %th Image
    %th Command
    %th Created at
    %th Status
    %th.container_ports Ports
    %th Names
    %th Actions
  - @containers_presenter.each do |container_presenter|
    %tr
      %td= container_presenter.display_id
      %td= container_presenter.display_image
      %td= container_presenter.command
      %td= container_presenter.created_at
      %td= container_presenter.status
      %td= container_presenter.ports
      %td= container_presenter.names
      %td
        - unless container_presenter.image.proxy? || container_presenter.image.administration?
          = link_to glyph('eye'), container_path(container_presenter.container.id)
          - if container_presenter.container.can_start?
            = link_to glyph('play'), start_container_path(container_presenter.container.id)
          - if container_presenter.container.can_stop?
            = link_to glyph('square'), stop_container_path(container_presenter.container.id)
          = link_to glyph('trash'), container_path(container_presenter.container.id), data: { method: :delete, confirm: 'Are you sure?'}

app/views/containers/new.html.haml
%h1 Containers#new
%p Find me in app/views/containers/new.html.haml