config/routes.rb
Rails.application.routes.draw do

  get 'settings/index'
  get 'settings/create_proxy'
  get 'settings/destroy_proxy'
  get 'home/index'
  get 'proxy/index' => 'proxy#index', as: :proxy
  get 'about/index' => 'about#index', as: :about
  get 'store/index' => 'store#index', as: :store

  resources :apps do
    member do
      get :restart
      get :start
      get :stop

      get :db_drop
      get :db_create
      get :db_migrate
      get :db_seed
    end
    collection do
      get :relaunch
      get :start_all
      get :stop_all
    end
  end

  resources :images do
    collection do
      post :destroy_all
    end
  end

  resources :containers do
    member do
      get :restart
      get :stop
      get :start
    end
    collection do
      get :destroy_unused
    end
  end

  root 'home#index'

end

app/views/apps/edit.html.haml
%h1= glyph_and_text HarbourCrane::Application::Glyph::APP, "Edit \"#{ @appname }\""

%br
= simple_form_for :app do |f|
  = row do
    = col num: 8 do
      %h2 Docker Compose
      = nav type: :tabs do |n|
        - n.link 'Rookie', url: '#compose-rookie', selector: 'compose-rookie'
        - n.link 'Expert', url: '#compose-expert', selector: 'compose-expert', status: :active
      %br
      .tab-content
        - bak_files = "#{ compose_app_dir(@app.id) }/*.bak-*"
        = f.input :upstart, label: "Upstart version", selected: @app.upstart_file_version, collection: version_array(Dir.glob(bak_files))

        = card tab: 'compose-rookie' do
          %h3 Container
          = card do
            = f.input :container_name, label: 'Name', placeholder: 'eq. web'
            = f.input :image, placeholder: "eq. docker/docker-manager:beta", hint: 'Must be registry_host[:registery_port]/name[:tag]'
            = f.input :ports, placeholder: 'eq. 3003:3000; 3002:3002'

            = f.input :environment, as: :text, placeholder: 'eq. RAILS_ENV:production; VIRTUAL_HOST: subdomain.domain.com'

            = f.input :links, placeholder: 'eq. db'

            %br

          = link_to glyph_and_text('plus-circle', 'New container'), "#"
        = card tab: 'compose-expert', status: :active do
          - file_path = "#{ compose_app_dir(@app.id) }/docker-compose.yml"
          = "File: #{ file_path }"
          - if File.exist?(file_path)
            = f.input :docker_compose, as: :text, input_html: { rows: 25, class: 'code', value: File.read(file_path) }
          - else
            %pre No file exist

    = col num: 4 do
      %h2 Volumes
      - dir_path = "#{ HarbourCrane::Application::VOLUME_DIR }/#{ @app.id }"
      - volumes = Dir.exist?(dir_path) ? Dir.entries(dir_path).reject{ |n| ['.', '..'].include?(n) } : []
      - volumes.each do |vol|
        = f.input :volume, label: false, as: :extra_text, disabled: true, append: glyph('folder-open'), prepend: 'x', input_html: { value: "#{ dir_path }/#{ vol }" }, placeholder: 'eq. logs; infos/public'

app/views/apps/index.html.haml
%h1= glyph_and_text App::GLYPH, "Apps listing"
%p List of apps in your server
%br
= row do
  = col num: 6 do
    = button_link 'Refresh', status: :primary, glyph: 'refresh', url: apps_path
    = button_link 'New App', status: :primary, glyph: 'plus-circle', url: new_app_path
  = col num: 6 do
    = button_link 'Relaunch all running apps', status: :danger, glyph: 'share', url: relaunch_apps_path
    = button_link 'Stop all', status: :primary, glyph: 'stop-circle', url: stop_all_apps_path
    = button_link 'Run all', status: :primary, glyph: 'play-circle', url: start_all_apps_path
%br
%br
%table.table
  %tr
    %th Actions
    %th Name
    %th Description
    %th Image
    %th State
    %th Created At
    %th Actions
  - @apps.each do |app|
    %tr
      %td
        = button_group size: :sm, class: 'upstart-action' do
          = button_link '', { glyph: 'play', url: start_app_path(app.id), state: app.running? ? :disabled : :default }, { title: 'Start' }
          = button_link '', { glyph: 'stop', url: stop_app_path(app.id),  state: app.running? ? :default : :disabled }, { title: 'Stop' }
          = button_link '', { glyph: 'refresh', url: restart_app_path(app.id), state: app.running? ? :default : :disabled }, { title: 'Restart' }
      %td= [app.name, app.proxy? ? etiquette('Proxy', status: :danger) : nil].compact.join(' ').html_safe
      %td= app.description
      %td= app.image
      %td= app.state
      %td= app.created_at
      %td
        = dropdown 'Action', glyph: 'ellipsis-v', size: :xs do |d|
          - d.header 'App actions'
          - d.link 'Edit', glyph: 'pencil', url: edit_app_path(app.id)
          - d.link 'Show', glyph: 'eye', url: app_path(app.id)
          - d.link 'Delete', { glyph: 'trash', url: app_path(app.id) }, { method: :delete, data: { confirm: 'Are you sure?' }}
          - d.divider
          - d.header 'Database actions'
          - d.link 'Drop', { glyph: 'trash', url: db_drop_app_path(app.id) }, { title: 'rails|rake db:drop', data: { confirm: 'Do you really want drop the database?' }}
          - d.link 'Create', { glyph: 'plus-circle', url: db_create_app_path(app.id) }, { title: 'rails|rake db:create', data: { confirm: 'Do you really want create the database?'} }
          - d.link 'Migrate', { glyph: 'share', url: db_migrate_app_path(app.id) } , { title: 'rails|rake db:migrate', data: { confirm: 'Do you really want create the database?'} }
          - d.link 'Seed', { glyph: 'th-list', url: db_seed_app_path(app.id) }, { title: 'rails|rake db:seed', data: { confirm: 'Do you really want create the database?'} }
          - d.link 'Import', { state: :disabled, glyph: 'th-list', url: db_seed_app_path(app.id) }, { title: 'rails|rake db:console <', data: { confirm: 'Do you really want create the database?'} }
          - d.link 'Export', state: :disabled, glyph: 'th-list', url: db_seed_app_path(app.id)
          - d.divider
          - d.header 'Other'
          - d.link 'Console', glyph: 'terminal', state: :disabled, url: '#'

app/views/apps/new.html.haml
%h1= glyph_and_text HarbourCrane::Application::Glyph::APP, "New app"

= simple_form_for @app do |f|
  = row do
    = col num: 6 do
      = f.input :name, placeholder: 'My app name'
    = col num: 6 do
      = f.input :slug, placeholder: 'my-app-name'
    = col num: 12 do
      = f.input :description, as: :text, placeholder: 'My description'

    = col num: 6 do
      = f.input :author, placeholder: 'Harbour Crane'
    = col num: 6 do
      = f.input :ports, placeholder: '3001:3000', readonly: true, input_html: { value: "#{ 3000 + App.all.count + 1 }:3000" }

    = col num: 6 do
      = f.input :image, as: :auto_complete_field, collection: Image.all.map{ |i| i.names.join(', ') }, placeholder: 'myname/myapp'
    = col num: 6 do
      = f.input :virtual_host, placeholder: 'myapp.domain.com'

    = col num: 12 do
      %label Volumes
      .ui-bibz-clear

    = col num: 12 do
      .form-group.volumes.optional
        .input-group
          %span.input-group-addon.path= "/srv/docker/my-app-name/"
          %input{ placeholder: "my-dir", type: "text", class: "volume_1 extra_text optional form-control" }
          %span.input-group-addon.separator= ":"
          %input{ placeholder: "/usr/src/app/public/system/", type: "text", class: "volume_2 extra_text optional form-control" }
        = f.input :volumes, label: false, as: :hidden

    = col num: 12 do
      = f.input :environment

    .ui-bibz-clear

    = col num: 12 do
      = card tap: true do |p|
        - p.header 'Import files'
        - p.block do
          = f.input :compose_file, as: :file, hint: 'docker-compose.yml'
      = button 'Submit', state: :primary

app/views/apps/show.html.haml
%h2= @app.name
= jumbotron do
  %p
    %strong Description:
    = @app.description
  %p
    %strong State:
    = @app.state
  %p
    %strong Created at:
    = @app.created_at