config/routes.rb
Rails.application.routes.draw do

  get 'settings/index'
  get 'settings/create_proxy'
  get 'settings/destroy_proxy'
  get 'home/index'
  get 'proxy/index' => 'proxy#index', as: :proxy
  get 'about/index' => 'about#index', as: :about
  get 'store/index' => 'store#index', as: :store

  resources :apps do
    member do
      get :restart
      get :start
      get :stop

      get :db_drop
      get :db_create
      get :db_migrate
      get :db_seed
    end
    collection do
      get :relaunch
      get :start_all
      get :stop_all
    end
  end

  resources :images do
    collection do
      post :destroy_all
    end
  end

  resources :containers do
    member do
      get :restart
      get :stop
      get :start
    end
    collection do
      get :destroy_unused
    end
  end

  root 'home#index'

end

app/models/image.rb
class Image
  include ActiveModel::Model

  attr_accessor :id, :name, :tag, :names, :size, :created_at

  def initialize attributes = {}
    attributes.each{ |k,v| instance_variable_set("@#{ k.to_s.underscore }", v) }
  end

  # Class methods  ##############################################################

  def self.all
    Docker::Image.all.map{ |i| self.new(Image::ConvertImage.new(i).attributes) }
  end

  # Find by name alone or with tag
  #  => hello-world or hello-world:beta
  def self.find_by_name name
    name_with_tag = name.split(':').count > 1 ? name : "#{ name }:latest"
    all.select{ |c| c.names.include?(name_with_tag) }.first
  end

  def self.find id
    all.select{ |c| c.id == without_hashing_method(id) }.first
  end

  # Return Image object
  def self.pull args
    new(Image::ConvertImage.new(Docker::Image.create('fromImage' => image_with_tag(args))).attributes)
  end

  def self.count
    Docker::Image.all.count
  end

  def self.first_or_create args
    raise 'name argument must be present.' if args[:name].nil?
    img = Image.find_by_name(args[:name])
    img.nil? ? pull(args) : img
  end

  def self.first
    all.first
  end

  def self.last
    all.last
  end

  # Object methods  ##############################################################

  def short_id
    id[0..12]
  end

  def proxy?
    names.include?(HarbourCrane::Application::PROXY_IMAGE_NAME)
  end

  def administration?
    names_without_tag.include?(HarbourCrane::Application::APP_IMAGE_NAME)
  end

  def protected?
    proxy? || administration?
  end

  def used?
    !names.select{ |name| Container.find_by_image(name) }.first.nil?
  end

  # Return Error
  def destroy force = false
    begin
      Docker::Image.get(id).remove(force: force)
    rescue => e
      errors.add e.message
    end
  end

  # Return Array with errors
  def self.destroy_all *ids
    ids.flatten.map do |id|
      image = self.find(id)
      unless image.nil?
        image.destroy
        image.errors.empty? ? nil : image.errors.full_messages.to_sentence
      else
        "Image #{id} not found"
      end
    end.compact
  end

  private

  def names_without_tag
    names.map{ |name| name.split(':')[0] }
  end

  def self.without_hashing_method str
    str.split(':').last
  end

  def without_hashing_method str
    str.split(':').last
  end

  def self.image_with_tag args
    "#{ args[:name] }:#{ args[:tag].blank? ? 'latest' : args[:tag] }"
  end

  self.singleton_class.send(:alias_method, :create, :pull)

end

app/models/image/convert_image.rb
class Image::ConvertImage
  include ActiveModel

  attr_accessor :id, :names, :name, :tag, :size, :created_at

  def initialize image
    @id         = without_hashing_method(image.id)
    @info       = image.info
    @names      = get_names
    @name       = get_name
    @tag        = get_tag
    @size       = get_size
    @created_at = get_date_time
  end

  def attributes
    { id: @id, names: @names, name: @name, tag: @tag, size: @size, created_at: @created_at }
  end

  private

  def get_date_time
    Time.at(@info['Created']).strftime(HarbourCrane::Application::TIME_FORMAT) unless @info['Created']
  end

  def without_hashing_method str
    str.split(':').last
  end

  def get_name
    @info['RepoTags'].first.split(':').first unless @info['RepoTags'].blank?
  end

  def get_tag
    @info['RepoTags'].first.split(':').last unless @info['RepoTags'].blank?
  end

  def get_names
    @info['RepoTags'] || []
  end

  def get_size
    @info['VirtualSize']
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :destroy]

  def index
    @images_presenter = ImagePresenter.new(Image.all).images
  end

  def new
    @image = Image.new
  end

  def show
  end

  def create
    @image = Image.pull(name: image_params[:name], tag: image_params[:tag])
    respond_to do |format|
      if @image
        format.html { redirect_to images_url, notice: 'Image was successfully added.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy_all
    params.permit!
    errors = Image.destroy_all(params[:ids].to_h.map{|k,_| k })
    respond_to do |format|
      if errors.empty?
        format.html { redirect_to images_url, notice: 'Images were successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to images_url, alert: errors.join(', ') }
        format.json { head :no_content }
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_image
    @image = Image.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:name, :tag)
  end

end

app/views/images/edit.html.haml
%h1 Images#edit
%p Find me in app/views/images/edit.html.haml

app/views/images/index.html.haml
%h1= glyph_and_text HarbourCrane::Application::Glyph::IMAGE, "Images listing"
%p List of images in your server
%br
= button_link 'Refresh', status: :success, glyph: 'refresh', url: images_path
= button_link 'New Image', status: :primary, glyph: 'plus-circle', url: new_image_path
= button_link 'Delete', { status: :danger, glyph: 'trash', url: destroy_all_images_path }, { id: 'delete_btn'}
%br
%br
= form_tag images_path, method: :post do
  %table.table.table-striped
    %thead
      %tr
        %th= checkbox_field :select_all, { label: '' }
        %th Image ID
        %th Name:Tag
        %th Created at
        %th Virtual Size
        %th Actions
      %tbody
        - @images_presenter.each_with_index do |image_presenter, i|
          %tr
            %td= checkbox_field "ids[#{image_presenter.id}]", { label: '' } unless image_presenter.image.protected?
            %td= image_presenter.display_id
            %td= image_presenter.names
            %td= image_presenter.created_at
            %td= image_presenter.size
            %td
              - unless image_presenter.image.protected?
                = link_to glyph('eye'), image_path(image_presenter.image.id)
                = link_to glyph('trash'), image_path(image_presenter.image.id), :method => :delete, :data => { :confirm => 'Are you sure?' }
    %tfoot
      %tr
        %td
        %td
          %b Total
        %td
        %td
        %td= number_to_human_size @images_presenter.sum{ |s| s.try(:image).try(:size) }
        %td

app/views/images/new.html.haml
%h1= glyph_and_text HarbourCrane::Application::Glyph::IMAGE, "New Image"

= simple_form_for @image do |f|#, method: :post, url: url_for(controller: :images, action: :create) do |f|
  = row do
    = col num: 10 do
      = f.input :name, placeholder: 'wordpress, ruby, php...', autofocus: true
    = col num: 2 do
      = f.input :tag, placeholder: 'latest, 3.3...'
    = col num: 12 do
      = f.submit 'Add Image', class: 'btn btn-primary'

app/views/images/show.html.haml
%h2= @image.names.join(', ')
= jumbotron do
  %p
    %strong Id:
    = @image.id
  %p
    %strong Created at:
    = @image.created_at
  %p
    %strong Size:
    = @image.size