config/routes.rb
Rails.application.routes.draw do

  get 'settings/index'
  get 'settings/create_proxy'
  get 'settings/destroy_proxy'
  get 'home/index'
  get 'proxy/index' => 'proxy#index', as: :proxy
  get 'about/index' => 'about#index', as: :about
  get 'store/index' => 'store#index', as: :store

  resources :apps do
    member do
      get :restart
      get :start
      get :stop

      get :db_drop
      get :db_create
      get :db_migrate
      get :db_seed
    end
    collection do
      get :relaunch
      get :start_all
      get :stop_all
    end
  end

  resources :images do
    collection do
      post :destroy_all
    end
  end

  resources :containers do
    member do
      get :restart
      get :stop
      get :start
    end
    collection do
      get :destroy_unused
    end
  end

  root 'home#index'

end

app/views/layouts/_flash_messages.html.haml
- flash.each do |msg_type, message|
  - if msg_type == "record_error"
    - if message.any?
      #error_explanation
        = notify(status: :danger) do
          %h2= "#{pluralize(message.count, "error")} prohibited this product from being saved:"
          %ul
            - message.each do |msg|
              %li= msg
  - else
    = notify(status: bootstrap_status_for(msg_type)) do
      %button.close{ data: { dismiss: 'alert' } } x
      = glyph_and_text bootstrap_icon_for(msg_type), message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= HarbourCrane::Application::NAME
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
    = favicon_link_tag 'black-crane.ico'
  %body
    = navbar do |nv|
      - nv.brand url: root_url do
        = image_tag 'grey-crane.png'
        = HarbourCrane::Application::NAME
      - nv.nav do |n|
        - n.link 'Apps', url: apps_path, status: active_link('apps')
        - n.link 'Images', url: images_path, status: active_link('images')
        - n.link 'Containers', url: containers_path, status: active_link('containers')
        - n.link 'Store', url: store_path, status: active_link('store')
        - n.link 'Proxy', url: proxy_path, status: active_link('proxy')
        - n.link 'About', url: about_path, status: active_link('about')
        - n.link 'Settings', url: settings_index_path, status: active_link('settings')
    - if controller_name == 'home'
      .pageheader
        = container do
          = yield :pageheader
    = container class: 'content', type: :fluid do
      = render "layouts/flash_messages"
      = yield